config/routes.rb
Videogames::Application.routes.draw do
  resources :tags,:games
  root :to=>'games#index'
  match '/tags',:to=>'tags#index'

  match '/games/getsearchresults/:q/:site',:to=>'games#getsearchresults'
  match '/getcommontags/:game1/:game2',:to=>'games#getcommontags'
  match '/results',:to=>'games#recommend_search'
  match '/searchimages',:to=>'games#searchimages'
  match '/browse',:to=>'games#browse'
  match '/loadnewgames/:id/:offset',:to=>'games#load_new_games'
  match '/mass_delete',:to=>'games#mass_delete',:via=>:post
  match '/dissociate/:game/:tag',:to=>'tags#dissociate'
  match '/associate',:to=>'tags#associate',:via=>:post
  match ':controller/:action/:id'
  match ':controller/:action'
end

app/views/partials/_child_tags_for_game.html.haml
- tags.each_with_index do |t,i|
  - if i % 3==0
    %br/
  %input{:type=>'checkbox',:name=>'tags[]', :value=>t.id, :class=>'tagbox',:rel=>t.name}>/
  #{t.name}&nbsp;&nbsp;

app/views/partials/_childtags.html.haml
- tags.each do |t|
  %tr{:class=>"#{t.parent}"}
    %td &raquo;&nbsp;&nbsp;&nbsp;#{t.name}
    %td= t.description
    %td= link_to 'View&nbsp;'.html_safe, t
    %td= link_to '&nbsp;Edit&nbsp;'.html_safe, edit_tag_path(t)
    %td
      %a{:class=>'destroy',:id=>t.id,:href=>'#'} &nbsp;Destroy

app/views/partials/_form.html.haml
%script{:type=>'text/javascript'}
  $(function() {
  $('.searchgame').click(function() {
  $.ajax({
  url:'/games/getsearchresults/'+$('#game_name').val()+'/'+$(this).attr('id'),
  type:'get',
  });
  });
  });

  $(function() {
  $('.tagbox').change(function() {
  if ($(this).is(':checked')) {
  $(this).parents('table').siblings('.parenttag').attr('checked',true);
  } else {
  $(this).parents('table').siblings('.parenttag').attr('checked',false);
  }
  });
  $('#parentselect').change(function() {
  var val=$(this).val();
  $.ajax({
  url:'/games/getparenttags/'+val,
  type:'get'
  });
  });
  $('.product_title a').live('click',function(e) {
  e.preventDefault();
  });
  $('.result_wrap').live('click',function(e) {
  e.preventDefault();
  href=$(this).find('.product_title a').attr('href');
  $.ajax({
  url:'/games/getgameinfo',
  type:'post',
  data:'href='+href+'&site=metacritic'
  });
  date=$(this).find('.release_date .data').html();
  name=$(this).find('.product_title a').html();
  rating=$(this).find('.metascore').html();
  if (date.length!=0) {
  year=date.slice(-4);
  $('#game_year').val(year);
  }
  if (rating.length!=0) {
  $('#game_rating').val(rating);
  }
  $('#game_name').val(name);
  $('#game_name').focus();
  $('#game_name').blur();
  });
  $('#gameselection .body table tr td a').live('click',function(e) {
  e.preventDefault();
  });
  $('.body table tr').live('click',function() {
  $('#game_name').val($(this).find('a').html());
  $('#game_name').focus();
  $('#game_name').blur();
  $('#game_rating').val(Math.round(parseFloat($(this).children('td').eq(3).find('b').html().slice(0,5))));
  $('#game_year').val($.trim($(this).children('td').eq(2).html()).slice(-4));
  var href=$(this).find('a').attr('href');
  $.ajax({
  url:'/games/getgameinfo',
  type:'post',
  data:'href='+href+'&site=gamerankings'
  });
  });
  $('#game_name').blur(function () {
  $.ajax({
  url:'/games/check_if_exists/'+$(this).val(),
  type:'get',
  dataType:'text',
  success:function(text) {
  $('#exists').html(text);
  }
  });
  });
  $('#gamespot_search').click(function() {
  $.ajax({
  url:'/games/getgamespotlink/'+$('#game_name').val()
  });
  });
  $('.tagname').click(function() {
  var checkbox=$(this).prev('input');
  if (checkbox.attr('checked')==false) {
  checkbox.attr('checked',true).change();
  } else {
  checkbox.attr('checked',false).change();
  }
  });
  
  });
  
= form_for(@game) do |f|
  - if @game.errors.any? 
    #error_explanation
      %h2 #{pluralize(@game.errors.count, "error")} prohibited this game from being saved:

      %ul
      - @game.errors.full_messages.each do |msg|
        %li= msg
  #gameselection
  .field{:style=>'margin-bottom:0;'}
    = f.label :name
    %br/
    = f.text_field :name
    %input{:type=>'button',:class=>'searchgame',:id=>'metacritic',:value=>'Metacritic'}
    %input{:type=>'button',:class=>'searchgame',:id=>'gamerankings',:value=>'GameRankings'}
  #exists
  .field{:style=>'display:inline-block;'}
    = f.label :year
    %br/
    = f.text_field (:year,:size=>5)
  .field{:style=>'display:inline-block;'}
    = f.label :rating
    %br/
    = f.text_field (:rating,:size=>5)
  .field{:style=>'display:inline-block;'}
    = f.label :parent
    %br/
    %select{:name=>"game[parent]",:id=>"parentselect"}
      %option{:value=>0} ---
      - @parents.each do |p|
        %option{:value=>p.id, :selected=> p.id==@game.parent }= p.name
  .field
    #{ f.check_box :type_of } Series
  
  .field
    = f.label :description
    %br/
    = f.text_area( :description,:cols=>50,:rows=>10)
    %br/
    %h2.boldtext Links
    #select_links
      #gamespot_selection
        %ul
      %input{:type=>'text',:class=>'linkfield'}
      %input{:type=>'button',:value=>'Gamespot',:id=>'gamespot_search'}
    %h2.boldtext Genres
    %table
      %tr
        = buildtags(@genres,@game).html_safe
    %br/
    %br/
    %h2.boldtext Platforms
    %table
      %tr
        = buildtags(@platforms,@game).html_safe
    %br/
    %br/
    %h2.boldtext Developers
    %table
      %tr
        = buildtags(@devs,@game).html_safe
    %br/
    %br/
    %h2.boldtext Themes
    %table
      %tr
        = buildtags(@themes,@game).html_safe
    %br/
    %br/
    %h2 Miscellaneous
    %table
      %tr
        = buildtags(@misc,@game).html_safe
  .actions
    = f.submit

app/views/partials/_fullinfo.html.haml
%span
  %span.boldtext Genre: 
  - genres.each do |g|
    - if g==genres.last
      = g.name
    - else
      #{g.name},
%br/
%span
  %span.boldtext Developer:
  - devs.each do |d|
    - if d==devs.last
      = d.name
    - else
      #{d.name},
%br/
%span
  %span.boldtext Platform:
  - platforms.each do |p|
    - if p==platforms.last
      = p.name
    - else
      #{p.name},
%br/
%span
  %span.boldtext Themes:
  - themes.each do |t|
    - if t==themes.last
      = t.name
    - else
      #{t.name},
%br/
%p= game.description

app/views/partials/_live_search_results.html.haml
%ul
  - search.each_hit_with_result do |h,g|
    %li
      - if g.type_of==1
        %a{:class=>'boldtext nothover',:href=>'#'} #{g.name} (series)
      - else
        %a{:class=>'nothover',:href=>'#'}= g.name

app/views/partials/_loaded_games.html.haml
- games.each do |game|
  - if game.type_of==1
    %tr{:class=>( game==games.last ? 'parent lastgame' : 'parent'),:rel=>game.id,:id=>( game==games.last ? "tr#{offset}" : "")}
      %td.checkcolumn
        %input{:type=>'checkbox',:name=>'mass[]',:value=>game.id}
      %td.namecolumn.boldtext= game.name
      %td{:colspan=>2}
      %td.boldtext
        =gettags(game).html_safe
      %td= link_to 'Show&nbsp;'.html_safe, game
      %td= link_to 'Edit&nbsp;'.html_safe, edit_game_path(game)
      %td
        %a{:class=>'destroy',:id=>game.id,:href=>'#'} Destroy
    = getchildgames game.id 
  - if game.type_of==0
    %tr{:class=>( game==games.last ? 'lastgame' : ''),:rel=>game.id,:id=>( game==games.last ? "tr#{offset}" : "")}
      %td.checkcolumn
        %input{:type=>'checkbox',:name=>'mass[]',:value=>game.id}
      %td= game.name
      %td= game.year
      %td= game.rating
      %td 
        =gettags(game).html_safe
      %td= link_to 'Show&nbsp;'.html_safe, game
      %td= link_to 'Edit&nbsp;'.html_safe, edit_game_path(game)
      %td
        %a{:class=>'destroy',:id=>game.id,:href=>'#'} Destroy

app/views/partials/_searchresults.html.haml
- results.each do |k,v|
  - v

app/views/partials/_stylesheets.html.haml
= stylesheet_link_tag 'scaffold'
= stylesheet_link_tag 'style'

app/views/partials/_taglist.html.haml
%table{:class=>'list'}
  %tr
    %th Name
    %th Description
    %th{:colspan=>3}
      
  - tags.each do |t|
    - if t.children==0
      %tr
        %td= t.name
        %td= t.description
        %td= link_to 'View&nbsp;'.html_safe, t
        %td= link_to '&nbsp;Edit&nbsp;'.html_safe, edit_tag_path(t)
        %td
          %a{:class=>'destroy',:id=>t.id,:href=>'#'} &nbsp;Destroy
    - if t.children>0
      %tr{:class=>'parent',:rel=>t.id}
        %td.boldtext= t.name
        %td.boldtext= t.description
        %td= link_to 'View&nbsp;'.html_safe, t
        %td= link_to '&nbsp;Edit&nbsp;'.html_safe, edit_tag_path(t)
        %td
          %a{:class=>'destroy',:id=>t.id,:href=>'#'} &nbsp;Destroy
      = getchildren t.id

  %br/