config/routes.rb
Videogames::Application.routes.draw do
  resources :tags,:games
  root :to=>'games#index'
  match '/tags',:to=>'tags#index'

  match '/games/getsearchresults/:q/:site',:to=>'games#getsearchresults'
  match '/getcommontags/:game1/:game2',:to=>'games#getcommontags'
  match '/results',:to=>'games#recommend_search'
  match '/searchimages',:to=>'games#searchimages'
  match '/browse',:to=>'games#browse'
  match '/loadnewgames/:id/:offset',:to=>'games#load_new_games'
  match '/mass_delete',:to=>'games#mass_delete',:via=>:post
  match '/dissociate/:game/:tag',:to=>'tags#dissociate'
  match '/associate',:to=>'tags#associate',:via=>:post
  match ':controller/:action/:id'
  match ':controller/:action'
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates_numericality_of :year,:greater_than=>1971,:less_than=>2015,:allow_blank=>true
  validates_numericality_of :rating,:greater_than=>0,:less_than=>101,:allow_blank=>true
  validates_presence_of :name
  has_many :associations,:foreign_key=>"game_id", :dependent=>:destroy
  has_many :reverse_associations,:foreign_key=>"tag_id",:class_name=>"Association"
  has_many :tags,:through=>:associations,:uniq=>true
  validates_associated :tags
  has_many :links
  attr_accessor :tag_ids
  after_create :update_tags
  after_update :update_tags
  
  searchable do
    text :name,:as=>:name_textp
  end
  
  
  def description=(val)
    write_attribute(:description,val.strip)
  end
  
  #this does the work of creating/updating game-tag associations
  def update_tags
    tags=self.tag_ids.clone
    unless tags.nil?
      self.associations.each do |a|
      #destroy an association if its tag wasn't checked in the form
        a.destroy unless tags.include?(a.tag_id.to_s)
      #for each existing association, delete its tag from the parameters(to prevent duplicate associations)
        tags.delete(a.tag_id.to_s)
      end
      devs=Tag.find(:all,:conditions=>'type_id=4',:select=>'id').map{|d| d.id.to_s}
      genres=Tag.find(:all,:conditions=>'type_id=2',:select=>'id').map{|g| g.id.to_s}
      if (tags&devs).length==0
        indie=Tag.find_by_name('Independent')
        # if no developer has been selected, assume "Independent"
        self.associations.create(:tag_id=>indie.id)
      end
      if (tags&genres).length==0
        other=Tag.find_by_name('Other')
        # if no genre has been selected, assume "Other"
        self.associations.create(:tag_id=>other.id)
      end
      tags.each do |t|
        self.associations.create(:tag_id=>t) unless t.blank?
      end
      reload
    end
  end
  
  
end

app/controllers/games_controller.rb
require 'rubygems'
require 'net/http'
require 'open-uri'
require 'nokogiri'
require 'htmlentities'
require 'sanitize'


def calc_sim(tags,issource)
  total=0
  platforms=0
  devs=0
  tags.each do |t|
    if t.type_id==3
      platforms+=1
    elsif t.type.id==4
      devs+=2
    end
    if t.type_id==2 and t.parent>0 then total+=1 end
    total+=t.type.value
  end
  if issource==true
    total=total-(devs+platforms)
  else
    total=total-(platforms-1) unless platforms<2 #if two games have more than one console in common it only counts as one.
  end 
  return total
end
  
# TO DO
#   game links
#   voting
#   get game images
#   user tag adding
#   usage notes on theme tags
#   result colors

class GamesController < ApplicationController
  def index
    @title='All games'
    @games = Game.order('LOWER(name) ASC').limit(LIST_OFFSET).find(:all,:conditions=>['parent=0'])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @games }
    end
  end


  def show
    @game = Game.find(params[:id])
    @title=@game.name
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @game }
    end
  end
  
  
  #this could almost certainly be improved
  def browse
    params=CGI.parse(request.query_string)
    @results=[]
    @tags=[]
    if params.length>0
      pvalues=[]
      params.each do |k,v|
        if v.kind_of?(Array)
          v.each { |w| pvalues.push(w) }
        else
          pvalues.push(v)
        end
      end
      pvalues.each do |p|
        if p==pvalues.first
          @results=Tag.find(p).games
        else
          derp=Tag.find(p).games
          @results=@results&derp
        end
        if p==pvalues.last
          @subtags=Tag.find_all_by_parent(p)
          @type=case Tag.find(p).type_id
            when 0 then 'misc'
            when 1 then 'genre'
            when 2 then 'platform'
            when 3 then 'dev'
            when 4 then 'theme'
          end
        end
        @tags.push(Tag.find(p))
      end
    end
    @misc,@genres,@platforms,@devs,@themes=Tag.find_types()
    render :layout=>'main'
  end
  
  
  def edit
    @title='Edit game'
    @game = Game.find(params[:id])
    @misc,@genres,@platforms,@devs,@themes=Tag.find_types()
    @parents=Game.order('name ASC').find(:all,:conditions=>["type_of=1 and parent=0"])
    @associations=@game.associations
  end


  def new
    @title='New game'
    @game = Game.new
    @misc,@genres,@platforms,@devs,@themes=Tag.find_types()
    @parents=Game.order('name ASC').find(:all,:conditions=>["type_of=1 and parent=0"])
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @game }
    end
  end
  
  
  def create
    game=params[:game]
    @game = Game.create!(:name=>game[:name],:year=>game[:year],:rating=>game[:rating],:description=>game[:description],:parent=>game[:parent],:type_of=>game[:type_of],:tag_ids=>params['tags'])
    @tags=Tag.all
    respond_to do |format|
      if @game.valid?
        format.html { redirect_to(:action=>'new') }
        format.xml  { render :xml => @game, :status => :created, :location => @game }
      else
        format.html { redirect_to( :action => "new") }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end


  def update
    @game = Game.find(params[:id])
    game=params[:game]
    respond_to do |format|
      if @game.update_attributes!(:name=>game[:name],:year=>game[:year],:rating=>game[:rating],:description=>game[:description],:parent=>game[:parent],:type_of=>game[:type_of],:tag_ids=>params['tags'])     
        format.html { redirect_to(:action=>'index') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  
  def load_new_games
    id=params[:id]
    offset=params[:offset].to_i
    @games=Game.order('LOWER(name) ASC').limit(LIST_OFFSET).offset(offset).find(:all,:conditions=>['parent=0'])
    @offset=offset+LIST_OFFSET
    respond_to do |format|
      format.js {render :layout=>false}
    end
  end
  
  
  #---perform a query with the recommendation engine.---#
  def recommend_search
    q=params['query']
    if params['query'][-8,8]=='(series)'
      type=1
      q.gsub!(' (series)','')
    else
      type=0
    end
    puts params['query'][0,-9]
    game=Game.find_by_type_of_and_name(type,q)
    @game=game.id
    tags=game.tags.find(:all,:conditions=>"children=0")
    games=Game.order('parent ASC').find(:all,:conditions=>['id != ?',game.id])
    games.insert(0,game)
    @indiv=[]
    @series=[]
    @full=0.0
    games.each do |g|
      sim=0.0
      relevance=0.0
      cmmn=(tags&g.tags)
      sim=calc_sim(cmmn,g==game)
      if g==game
        @full=sim
      else
        total=calc_sim(g.tags,true)
        source_total=calc_sim(tags,true)
        sim=sim-(((total/source_total)/10)*sim) #penalty for when the compared game has much greater tags than the source game 
        if sim>@full*0.5 #arbitrary, this could be better
          if g.rating==nil then rating=101 else rating=g.rating end
          ratio=sim/@full>1 ? 1 : sim/Float(@full)
          puts "#{g.name}: #{sim},#{@full},#{ratio},#{rating},#{Float(sim/@full)}"
          relevance=Float((ratio+rating/100.0)/2) #this could probably be improved
          
          if g.type_of==0
            @indiv.push({:game=>g,:sim=>sim,:relevance=>relevance})
          else
            @series.push({:game=>g,:sim=>sim,:relevance=>relevance})
          end
        end
      end
    end
    @indiv=@indiv.sort {|a,b| [ a[:relevance] ] <=> [b[:relevance] ]}.reverse
    @series=@series.sort {|a,b| [ a[:relevance] ] <=> [b[:relevance] ]}.reverse
    @misc,@genres,@platforms,@devs,@themes=Tag.find_types()
    render :layout=>'main'
  end
  
  
  def mass_delete
    params[:mass].each do |m|
      Game.destroy(m)
    end
    redirect_to(:action=>'index')
  end 
  
  #------------------------AJAX ACTIONS----------------------------#
  
  
  def destroy
    respond_to do |format|
      if request.xhr?
        @game = Game.find(params[:id])
        if @game.destroy
          format.js {render :json=>{:status=>:ok}}
        else
          format.js {render :json=>{:status=>:error}}
        end
      else 
        format.html { redirect_to(:action=>'index') }
      end
    end
  end
  
  
  def livesearch
    @search=Game.search do
      keywords(params[:id])
    end

    respond_to do |format|
      format.js {render :layout=>false}
    end
  end
  
  
  #---get the search results of the game name on either metacritic or gamerankings via ajax.---#
  def getsearchresults
    query=params['q'].gsub(' ','+')
    query=query.gsub('/','%2F')
    if params[:site]=='metacritic'
      doc=Nokogiri::HTML(open("http://metacritic.com/search/game/#{query}/results"))
      doc.encoding='utf-8'
      @results=doc.css("li.result").inner_html
    elsif params[:site]=='gamerankings'
      doc=Nokogiri::HTML(open("http://www.gamerankings.com/browse.html?search=#{query}&numrev=3"))
      @results=doc.at_css("div#main_col > div.pod").inner_html
    end
    respond_to do |format|
      format.js {render :layout => false}
    end
  end
  
  def getgameinfo
    if params[:site]=='metacritic'
      doc=Nokogiri::HTML(open("http://metacritic.com#{params['href']}"))
      doc.encoding='utf-8'
      blurb1=''
      blurb2=''
      doc.css("li.summary_detail.product_summary").each do |s|
        if s.at_css('span.blurb').inner_html == nil
          blurb1=s.at_css('span.data').inner_html
        else
          blurb1=s.at_css("span.blurb.blurb_collapsed").inner_html
          blurb2=s.at_css("span.blurb.blurb_expanded").inner_html
        end
      end
      @desc=(blurb1+blurb2).strip
      @desc.gsub!(/\[[A-z\s1-2]*\]/,'')
      @platforms=[]
      doc.css("span[@class='platform']").each do |p|
        platform=p.at_css('a').content
        @platforms.push(platform)
      end
      doc.css("li.summary_detail.product_platforms").each do |p|
        p.css('a').inner_html.each do |a|
          @platforms.push(a)
        end
      end
      doc.css("li.summary_detail.developer").each do |d|
        @dev=d.at_css("span.data").inner_html
        @dev.strip!
      end
      
    elsif params[:site]=='gamerankings'
      doc=Nokogiri::HTML(open("http://gamerankings.com#{params[:href]}"))
      doc.encoding='utf-8'
      @desc=doc.at_css("div.pod[2] > div.body > div.details").children.select{|e| e.text?}.join('')
      @desc.strip!
    end
    respond_to do |format|
      format.js {render :layout => false}
    end
  end
  
  def getparenttags
    game=Game.find(params[:id])
    @tags=game.associations
    respond_to do |format|
      format.js {render :layout=>false}
    end
  end

  def check_if_exists
    name=params[:id]
    if Game.exists?(:name=>name,:type_of=>0) then render :text=>'Exists as a <span class="boldtext">game</span>.' and return end
    if Game.exists?(:name=>name,:type_of=>1) then render :text=>'Exists as a <span class="italictext">series</span>.' and return end
    render :text=>'' and return
  end
  
  
  def getcommontags
    tags1=Game.find(params[:game1]).tags
    tags2=Game.find(params[:game2]).tags
    cmmn=(tags1&tags2)
    s="&nbsp;&nbsp;"
    cmmn.each do |c|
      if c==cmmn.last
        s+="#{c.name}"
      else
        s+="#{c.name} - "
      end
    end
    render :text=>s
  end
  
  
  def getalltags
    s=""
    tags=Game.find(params[:id]).tags
    tags.each do |t|
      if t==tags.last
        s+="#{t.name}"
      else
        s+="#{t.name} - "
      end
    end
    render :text=>s
  end
  
  
  def getgamespotlink
    query=params['id'].gsub(' ','+')
    query=query.gsub('/','%2F')
    doc=Nokogiri::HTML(open("http://gamespot.com/search.html?qs=#{params['q']}"))
    doc.encoding='utf-8'

app/helpers/games_helper.rb
require 'rubygems'
require 'htmlentities'

module GamesHelper
  def getchildtags(id,game)
    s="<table><tr>"
    children=Tag.order('name ASC').find_all_by_parent(id)
    children.each_with_index do |t,i|
      if i>0 and i % 3==0 then s+="</tr><tr>" end
      s+="<td><input type='checkbox' name='tags[]' value=#{t.id} class='tagbox' rel='#{t.name}' /"
      if game.tags.include?(t) then s+=" checked=checked " end
      s+="><span class='tagname'>#{t.name}</span></td>"
      
    end
    s+="</tr></table>"
    return s
  end
  
  def getchildgames(id)
    games=Game.order('year ASC').find_all_by_parent(id)
    render(:partial=>'childgames',:locals=>{:games=>games})
  end
  
  def gettags(game)
    tags=game.tags.all
    s=''
    tags.each do |t|
      if t==tags.last
        s+="<span class='type#{t.type_id}'>#{t.name} </span>" 
      else
        s+="<span class='type#{t.type_id}'>#{t.name}, </span>" 
      end
    end
    return s
  end
  
  def buildtags(tags,game)
    s="<td valign='top'>"
    tags.each.with_index do |t,i|
      if t.children >= 1
        s+="<br/><div class='taglist'>
          <span class='boldtext'>#{t.name}</span>"
        if t.type_id!=5
          s+="<input type='checkbox' class='parenttag' value=#{t.id} name='tags[]'  />"
        end
        s+=getchildtags(t.id,game)+"<br/></div>"
      else
        s+="<input type='checkbox' rel='#{t.name}' name='tags[]' value=#{t.id} class='tagbox'"
        if game.tags.include?(t) then s+=" checked=checked " end
        s+="/>
        <span class='tagname'>#{t.name}</span>&nbsp;&nbsp;<br/>"
      end
      if i>0 && i%10==0 then s+="</td><td valign='top'>" end
    end
    s+="</td></div>"
    return s
  end
  
  def build_browsing_category(tags,type,mode)
    s="<ul class='#{mode}'>"
    current=request.query_string
    current.gsub!(/(query=.*)/,'')
    if current.length>0
      current='?'+current+'&'
    else
      current='?'
    end
    tags.each do |t|
      s+="<li>"+build_tag_link(current,type,t)
      if t.children>0
        s+=build_browsing_category(Tag.find_all_by_parent(t.id),type,mode)
      end
      s+="</li>"
    end
    s+="</ul>"
    return s
  end
  
  def build_tag_link(current,type,t)
    return "<a href='/browse#{current}#{type}=#{t.id}'>#{t.name}</a>"
  end
  
  def get_rating_color(ratio)
    if ratio>1 then color='purple' end
    if ratio<=1 && ratio>=0.9 then color='red' end
    if ratio<0.9 && ratio>=0.75 then color='orange' end
    if ratio<0.75 && ratio>=0.5 then color='yellow' end
    return color
  end
end

app/views/games/_childgames.html.haml
- games.each do |g|
  %tr{:class=>"#{g.parent}",:rel=>g.id}
    %td.checkcolumn
      %input{:type=>'checkbox',:name=>'mass[]',:value=>g.id}
    %td &raquo;&nbsp;&nbsp;&nbsp;#{g.name}
    %td= g.year
    %td= g.rating
    %td
      =gettags(g).html_safe
    %td= link_to 'Show', g
    %td= link_to 'Edit', edit_game_path(g)
    %td= link_to 'Destroy', g, :confirm => 'Are you sure?', :method => :delete

app/views/games/_childtags.html.haml
- tags.each_with_index do |t,i|
  - if i % 3==0
    %br/
  %input{:type=>'checkbox',:name=>'tags[]', :value=>t.id, :class=>'tagbox',:rel=>t.name}>/
  #{t.name}&nbsp;&nbsp;

app/views/games/_form.html.haml
%script{:type=>'text/javascript'}
  $(function() {
  $('.searchgame').click(function() {
  $.ajax({
  url:'/getsearchresults',
  type:'post',
  data:'q='+$('#game_name').val()+'&site='+$(this).attr('id')
  });
  });
  });

  $(function() {
  $('.tagbox').change(function() {
  $(this).siblings('.parenttag').attr('checked','checked');
  });
  $('#parentselect').change(function() {
  var val=$(this).val();
  $.ajax({
  url:'/getparenttags',
  type:'post',
  data:'parent='+val
  });
  });
  $('.product_title a').live('click',function(e) {
  e.preventDefault();
  });
  $('.result_wrap').live('click',function(e) {
  e.preventDefault();
  href=$(this).find('.product_title a').attr('href');
  $.ajax({
  url:'/getgameinfo',
  data:'href='+href+'&site=metacritic',
  type:'post'
  });
  date=$(this).find('.release_date .data').html();
  name=$(this).find('.product_title a').html();
  rating=$(this).find('.metascore').html();
  if (date.length!=0) {
  year=date.slice(-4);
  $('#game_year').val(year);
  }
  if (rating.length!=0) {
  $('#game_rating').val(rating);
  }
  $('#game_name').val(name);
  });
  $('#gameselection .body table tr td a').live('click',function(e) {
  e.preventDefault();
  });
  $('.body table tr').live('click',function() {
  $('#game_name').val($(this).find('a').html());
  $('#game_rating').val(Math.round(parseFloat($(this).children('td').eq(3).find('b').html().slice(0,5))));
  $('#game_year').val($.trim($(this).children('td').eq(2).html()).slice(-4));
  var href=$(this).find('a').attr('href');
  $.ajax({
  url:'/getgameinfo',
  data:'href='+href+'&site=gamerankings',
  type:'post'
  });
  });
  });
  
= form_for(@game) do |f|
  - if @game.errors.any? 
    #error_explanation
      %h2 #{pluralize(@game.errors.count, "error")} prohibited this game from being saved:

      %ul
      - @game.errors.full_messages.each do |msg|
        %li= msg
  #gameselection
  .field
    = f.label :name
    %br/
    = f.text_field :name
    %input{:type=>'button',:class=>'searchgame',:id=>'metacritic',:value=>'Metacritic'}
    %input{:type=>'button',:class=>'searchgame',:id=>'gamerankings',:value=>'GameRankings'}
  .field
    = f.label :year
    %br/
    = f.text_field :year
  .field
    = f.label :rating
    %br/
    = f.text_field :rating 
  .field
    #{ f.check_box :type_of } Series
  .field
    = f.label :parent
    %br/
    %select{:name=>"game[parent]",:id=>"parentselect"}
      %option{:value=>0} ---
      - @parents.each do |p|
        %option{:value=>p.id}= p.name
  .field
    = f.label :description
    %br/
    = f.text_area :description
    %br/
    %h2.boldtext Genres
    %table
      %tr
        = buildtags(@genres,@game).html_safe
    %br/
    %br/
    %h2.boldtext Platforms
    %table
      %tr
        = buildtags(@platforms,@game).html_safe
    %br/
    %br/
    %h2.boldtext Developers
    %table
      %tr
        = buildtags(@devs,@game).html_safe
    %br/
    %br/
    %h2.boldtext Themes
    %table
      %tr
        = buildtags(@themes,@game).html_safe
    %br/
    %br/
    %h2 Miscellaneous
    %table
      %tr
        = buildtags(@misc,@game).html_safe
  .actions
    = f.submit

app/views/games/browse.html.haml
= content_for :results do
  - if @tags.any?
    =link_to '<h3 id="reset">Reset</h3>'.html_safe,'/browse',:id=>'reset_link'
  - @tags.each do |t|
    - if t==@tags.last
      %h3= t.name
      -if @subtags.any?
        = build_browsing_category(@subtags,@type,'browsing_subtags').html_safe
    - else
      %h3 #{t.name} /
  - if @results.any?
    - @results.each do |r|
      %ul.searchresults
        %li
          %h4= r.name 

app/views/games/getfullinfo.js.haml
$(".fullinfo[rel=#{@game.id}] .expanded_info").append("#{escape_javascript(render(:partial=>'partials/fullinfo',:locals=>{:game=>@game,:misc=>@misc,:platforms=>@platforms,:genres=>@genres,:devs=>@devs,:themes=>@themes})) }");

app/views/games/getgameinfo.js.erb
$("#game_description").html("<%= escape_javascript(@desc) %>");
<% if !@platforms.nil? %>
  <% @platforms.each do |p| %>
    $('input[rel=<%=p%>]').attr('checked','checked');
  <% end %>
<% end %>
<% if !@dev.nil? %>
  $('input[rel=<%=@dev%>]').attr('checked','checked');
<% end %>

app/views/games/getparenttags.js.haml
- @tags.each do |t|
  $(".tagbox[value=#{t.tag_id}]").attr('checked',true).change();

app/views/games/getsearchresults.js.erb
$("#gameselection").html('<%= escape_javascript(render(:partial=>'partials/searchresults',:locals=>{:results=>@results})) %>');

app/views/games/livesearch.js.erb
$('#live_search_results').html("<%= escape_javascript(render(:partial=>'partials/live_search_results',:locals=>{:search=>@search})) %>");

app/views/games/load_new_games.js.erb
$(".list").append('<%= escape_javascript(render(:partial=>'partials/loaded_games',:locals=>{:games=>@games,:offset=>@offset})) %>');

app/views/games/new.html.haml
%script{:type=>'text/javascript'}
  $(function() {
  $('.tags').each(function() {
  var val=$(this).val();
  $('.tagbox').val(val).attr('selected','selected');
  });
  });

%h1 New game

= render 'partials/form'

= link_to 'Back', games_path

app/views/games/recommend_search.html.haml
= content_for :results do
  %script{:type=>'text/javascript'}
    $(function() {
    $('.viewcommon').click(function(e) {
    e.preventDefault();
    var thisgame=$(this).attr('rel');
    var sourcegame=#{@game}
    $.ajax({
    url:'/getcommontags/'+sourcegame+'/'+thisgame,
    dataType:'html',
    success:function(data) {
    $('.viewcommon[rel='+thisgame+']').html('View all tags').attr('class','viewalltags').after(data);
    }
    });
    });
    $('.viewalltags').live('click',function() {
    var id=$(this).attr('rel');
    $.ajax({
    url:'/games/getalltags/'+id,
    dataType:'html',
    success:function(data) {
    $('.viewalltags[rel='+id+']').parent().html(data);
    }
    });
    });
    $('.expandinfo').toggle(function(e) {
    e.preventDefault();
    $(this).next('.expanded_info').show();
    if ($(this).next('.expanded_info').html()=='') {
    $.ajax({
    url:'/games/getfullinfo/'+$(this).attr('rel')
    });
    }
    $(this).html('Collapse');
    },function(e) {
    e.preventDefault();
    var next=$(this).next('.expanded_info');
    next.hide();
    $(this).html('Expand');
    });
    });
    
  %h2 Games
  %ul.searchresults
    - @indiv.each do |i|
      %li
        %h4= i[:game].name
        - if i[:game].rating != nil
          %h4 &nbsp;-&nbsp;
          %h4.rating= i[:game].rating
        %br/
        %span.boldtext Similarity: 
        #{i[:sim]}/#{@full}
        %br/
        %span.boldtext Relevance: 
        = i[:relevance]
        .fullinfo{:rel=>i[:game].id}
          %a{:href=>'#',:class=>'expandinfo',:rel=>i[:game].id} Expand
          .expanded_info
        .commontags
          %a{:href=>'#',:class=>'viewcommon',:rel=>i[:game].id} View common tags
  %h2 Series
  %ul.searchresults
    - @series.each do |s|
      %li
        %h4 #{s[:game].name}
        - if s[:game].rating != nil
          &nbsp;-&nbsp;
          %h4.rating= s[:game].rating
        %br/
        %span.boldtext Similarity: #{s[:sim]}/#{@full}
        %br/
        %span.boldtext Relevance: #{s[:relevance]}
        %br/

app/views/games/searchresults.html.haml
= content_for :results do
  %h2 Games
  %ul.searchresults
    - @indiv.each do |k,v|
      %li 
        %h4= k.name
        %h4{:class=>"#{get_rating_color(v,@full)}"} #{v}/#{@full}
  %h2 Series
  %ul.searchresults
    - @series.each do |k,v|
      %li
        %h4= k.name
        %h4{:class=>"#{get_rating_color(v,@full)}"} #{v}/#{@full}

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @game.name %>
</p>

<p>
  <b>Year:</b>
  <%= @game.year %>
</p>

<p>
  <b>Description:</b>
  <%= @game.description %>
</p>

<p>
  <b>Rating:</b>
  <%= @game.rating %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>